spring.application.name=project-to-dev

spring.config.import=classpath:/env.properties
 

 spring.sql.init.mode=always
spring.datasource.url=${database.url}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
 

 
 
spring.data.web.pageable.max-page-size=45
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.serialization-mode=via-dto
